### ISSUE TITLE
"Follow" option appears on your own profile

### ISSUE THREAD

**Issue by numbertheory** [seldo/alpaca#44]
It seems on the `alpaca.blue` UI you can click to follow yourself, but doing that doesn't add a follower in the other interfaces. In other Mastodon apps, there is no option to follow yourself, it's replaced by an "Edit Profile" button.

**Comment by seldo** [comment]
These are all great, thank you! Some of them are dupes of "drafts" I was already tracking (this is a "dupe" of what is now #45 after I turned it into an issue). You can see the drafts on the project kanban: https://github.com/users/seldo/projects/1/views/1
